- name: ECS用のAWS_ACCESS_KEYの登録
  community.aws.aws_secret:
    state: present
    name: "aws_access_key"
    secret_type: "string"
    secret: "{{ ecs_aws_access_key }}"
  register: aws_access_key_info

- name: ECS用のAWS_SECRET_KEYの登録
  community.aws.aws_secret:
    state: present
    name: "aws_secret_key"
    secret_type: "string"
    secret: "{{ ecs_aws_secret_key }}"
  register: aws_secret_key_info

  # - name: ECS用のASSUME_ROLEの登録
  #   community.aws.aws_secret:
  #     state: present
  #     name: "aws_assume_role"
  #     secret_type: "string"
  #     secret: "{{ ecs_aws_assume_role }}"
  #   register: aws_assume_role_info
