- name: ParameterStoreにAWS_ACCESS_KEYの削除
  community.aws.aws_secret:
    state: absent
    name: "aws_access_key"
    secret_type: "string"
    secret: "{{ ecs_aws_access_key }}"
    recovery_window: "{{ secret_recovery_window }}"
  register: delete_aws_acces_key_info
  ignore_errors: true

- name: ParameterStoreにECS用のAWS_SECRET_KEYの削除
  community.aws.aws_secret:
    state: absent
    name: "aws_secret_key"
    secret_type: "string"
    secret: "{{ ecs_aws_secret_key }}"
    recovery_window: "{{ secret_recovery_window }}"
  register: delete_aws_secret_key_info
  ignore_errors: true

  # - name: ParameterStoreにECS用のASSUME_ROLEの削除
  #   community.aws.aws_secret:
  #     state: absent
  #     name: "aws_assume_role"
  #     secret_type: "string"
  #     secret: "{{ ecs_aws_assume_role }}"
  #     recovery_window: "{{ secret_recovery_window }}"
  #   register: delete_aws_assume_role_info
  #   ignore_errors: true
