- name: VPCを作成
  amazon.aws.ec2_vpc_net:
    state: present
    name: "{{ ec2_vpc_name }}"
    cidr_block: "{{ ec2_vpc_cidr }}"
  register: ec2_vpc

- name: VPCのサブネットAを作成
  amazon.aws.ec2_vpc_subnet:
    state: present
    az: "{{ ec2_vpc_subnet_a_az }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    cidr: "{{ ec2_vpc_subnet_a_cidr }}"
    tags:
      Name: "{{ ec2_vpc_subnet_a_name }}"
  register: ec2_vpc_subnet_a

- name: VPCのサブネットCを作成
  amazon.aws.ec2_vpc_subnet:
    state: present
    az: "{{ ec2_vpc_subnet_c_az }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    cidr: "{{ ec2_vpc_subnet_c_cidr }}"
    tags:
      Name: "{{ ec2_vpc_subnet_c_name }}"
  register: ec2_vpc_subnet_b

- name: VPCのサブネットDを作成
  amazon.aws.ec2_vpc_subnet:
    state: present
    az: "{{ ec2_vpc_subnet_d_az }}"
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    cidr: "{{ ec2_vpc_subnet_d_cidr }}"
    tags:
      Name: "{{ ec2_vpc_subnet_d_name }}"
  register: ec2_vpc_subnet_d

- name: VPCのインターネットゲートウェイを作成
  community.aws.ec2_vpc_igw:
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    state: present
    tags:
      Name: "{{ ec2_vpc_igw_name }}"
  register: ec2_vpc_igw

- name: VPCのルートテーブルを作成
  community.aws.ec2_vpc_route_table:
    vpc_id: "{{ ec2_vpc.vpc.id }}"
    subnets:
      - "{{ ec2_vpc_subnet_a_name }}"
      - "{{ ec2_vpc_subnet_c_name }}"
      - "{{ ec2_vpc_subnet_d_name }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ ec2_vpc_igw.gateway_id }}"
    tags:
      Name: "{{ ec2_vpc_rtb_name }}"
  register: ec2_vpc_rtb
