- name: VPCのルートテーブルを削除
  community.aws.ec2_vpc_route_table:
    state: absent
    vpc_id: "{{ ec2_vpc_id }}"
    tags:
      Name: "{{ ec2_vpc_rtb_name }}"
  register: ec2_vpc_rtb

- name: VPCのサブネットAを削除
  amazon.aws.ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ ec2_vpc_id }}"
    cidr: "{{ ec2_vpc_subnet_a_cidr }}"
    tags:
      Name: "{{ ec2_vpc_subnet_a_name }}"
  register: ec2_vpc_subnet_a

- name: VPCのサブネットCを削除
  amazon.aws.ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ ec2_vpc_id }}"
    cidr: "{{ ec2_vpc_subnet_c_cidr }}"
    tags:
      Name: "{{ ec2_vpc_subnet_c_name }}"
  register: ec2_vpc_subnet_b

- name: VPCのサブネットDを削除
  amazon.aws.ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ ec2_vpc_id }}"
    cidr: "{{ ec2_vpc_subnet_d_cidr }}"
    tags:
      Name: "{{ ec2_vpc_subnet_d_name }}"
  register: ec2_vpc_subnet_c

- name: VPCのインターネットゲートウェイを削除
  community.aws.ec2_vpc_igw:
    state: absent
    vpc_id: "{{ ec2_vpc_id }}"
    tags:
      Name: "{{ ec2_vpc_igw_name }}"
  register: ec2_vpc_igw

- name: VPCを削除
  amazon.aws.ec2_vpc_net:
    state: absent
    name: "{{ ec2_vpc_name }}"
    cidr_block: "{{ ec2_vpc_cidr }}"
  register: ec2_vpc