- name: VPCの情報を取得
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_vpc_name }}"
  register: ec2_vpc_net_info

- set_fact:
    ec2_vpc_id: "{{ ec2_vpc_net_info.vpcs[0].id }}"
  when: ec2_vpc_net_info.vpcs|length > 0

- name: VPCのサブネット情報の取得
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ ec2_vpc_id }}"
  register: subnet_info
  when: ec2_vpc_id is defined

- set_fact:
    ec2_vpc_subnet_ids: "{{ subnet_info.subnets|map(attribute='id')|list }}"
  when: subnet_info.subnets is defined