---
- hosts: all
  connection: local
  environment:
    AWS_PROFILE: "{{ aws_profile }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  tasks:
  - name: VPCを作成
    tags:
      - aws/ec2_vpc
    import_role:
      name: aws/ec2_vpc
      tasks_from: create_ec2_vpc