---
- hosts: all
  connection: local
  environment:
    AWS_PROFILE: "{{ aws_profile }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  tasks:
  - name: RDSインスタンスを作成
    tags:
      - aws/rds
    import_role:
      name: aws/rds
      tasks_from: create_rds_instance